sudo: required
dist: trusty

language: php
node_js:
- "8"
php:
- 7.1

cache:
  yarn: true
  directories:
  - node_modules
  - vendor

notifications:
  email:
    on_success: never
    on_failure: never

env:
- NODE_RELEASE=8.x

before_install:
- sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
- sudo apt-get install -y nodejs

install:
- composer install
- yarn


stages:
- unit
- integration
#- coverage
#- deploy

jobs:
  include:
  - stage: unit
    name: "JavaScript Unit Tests"
    script: yarn test:once
  - # stage name not required, will continue to use `unit`
    name: "PHP Unit Tests"
    script: composer test:unit
  - stage: integration
    name: "WordPress Integration Tests"
    script: composer wp:install && composer wp:tests

